title: Ultimate repo for embedded devices
email: mail@entware.net
description: >- # this means to ignore newlines until "baseurl:"
  A software repository for network attached storages, routers and other embedded devices

url: "https://github.com/Entware/entware"
#twitter_username: darkade
github_username: Entware
rss: RSS

show_excerpts: true

header_pages:
 - about.md

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 4
paginate_path: posts/page:num/
