title: Ultimate repo for embedded devices
author: Entware team
email: mail@entware.net
description: >- # this means to ignore newlines until "minima:"
  A software repository for network attached storages, routers and other embedded devices

minima:
  social_links:
    github: Entware
    telegram: entware

header_pages:
 - about.md
 - archive.md

markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 6
paginate_path: posts/page:num/
